# Generated by Django 4.1 on 2023-05-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='密钥')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj', to='chat.user', verbose_name='对象')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='chat.user', verbose_name='用户')),
            ],
        ),
    ]
