# Generated by Django 4.1 on 2023-05-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_secretkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '已同意'), (2, '已拒绝')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_obj', to='chat.user', verbose_name='对象')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to='chat.user', verbose_name='用户')),
            ],
        ),
    ]
