# Generated by Django 4.1 on 2023-05-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_application_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretkey',
            name='key',
            field=models.CharField(max_length=100, verbose_name='密钥'),
        ),
    ]
